### ISSUE TITLE
Too many css files

### ISSUE THREAD

**Issue by MahmodMhamed** [WebAhead10/FAN#2]
There is no need for this amount of css fiels.
you can only keep one file.

Let's imagine the following scenario:
If you want to change the style for somthing, you probably take a bit of time to find in which file exactly need to change, instead one file that simply searching some class or tag or id.

**Comment by noor-sawaed** [comment]
all you need is a static file: "user-style.css" that works as a template for all users also works for new signed up users which will not affect the users that are already are in the student list.

**Comment by Nida1987** [comment]
Done !
